exclude_paths:
- "src/css/"
- "src/fonts/"
- "src/images/"
- "src/js/dependencies/"
- "**.html"
engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths: []
